import type {
  Booking,
  MedicalRecord,
  Nurse,
  NurseWallet,
  ServiceCategory,
  SessionBooking,
} from './types'

// جميع محافظات جمهورية مصر العربية (27 محافظة)
export const GOVERNORATES = [
  'القاهرة',
  'الجيزة',
  'الإسكندرية',
  'القليوبية',
  'الدقهلية',
  'الشرقية',
  'المنوفية',
  'الغربية',
  'كفر الشيخ',
  'دمياط',
  'بورسعيد',
  'الإسماعيلية',
  'السويس',
  'شمال سيناء',
  'جنوب سيناء',
  'الفيوم',
  'بني سويف',
  'المنيا',
  'أسيوط',
  'سوهاج',
  'قنا',
  'الأقصر',
  'أسوان',
  'البحر الأحمر',
  'الوادي الجديد',
  'مطروح',
  'البحيرة',
]

export const SERVICES: ServiceCategory[] = [
  {
    id: 'post-op',
    title: 'رعاية ما بعد العمليات',
    description:
      'متابعة دقيقة بعد الجراحة تشمل تغيير الغيارات، متابعة الأدوية، والعناية بالجرح لتعافٍ آمن في المنزل.',
    icon: 'Stethoscope',
  },
  {
    id: 'wound-care',
    title: 'غيار الجروح والتقرحات',
    description:
      'تنظيف وتعقيم الجروح والتقرحات وقرح الفراش باستخدام أدوات معقمة وبروتوكولات طبية معتمدة.',
    icon: 'Bandage',
  },
  {
    id: 'injections',
    title: 'الحقن والمحاليل الطبية',
    description:
      'إعطاء الحقن العضلية والوريدية وتركيب المحاليل الطبية بأمان تام وعلى يد ممرض محترف.',
    icon: 'Syringe',
  },
  {
    id: 'newborn',
    title: 'رعاية حديثي الولادة والأم',
    description:
      'العناية بالمولود والأم بعد الولادة، الرضاعة، متابعة الوزن والعلامات الحيوية والدعم المنزلي.',
    icon: 'Baby',
  },
  {
    id: 'physio',
    title: 'جلسات العلاج الطبيعي',
    description:
      'جلسات علاج طبيعي مبدئية لإعادة التأهيل الحركي وتخفيف الآلام تحت إشراف أخصائي معتمد.',
    icon: 'Activity',
  },
  {
    id: 'elderly',
    title: 'مرافقة ورعاية كبار السن',
    description:
      'رعاية شاملة لكبار السن تشمل المتابعة اليومية، الأدوية، والمرافقة الإنسانية والصحية.',
    icon: 'Users',
  },
  {
    id: 'emergency',
    title: 'إسعافات أولية طارئة',
    description:
      'دعم إسعافي أولي سريع للحالات الطارئة قبل الوصول للمستشفى مع توجيه فوري للطوارئ.',
    icon: 'Ambulance',
  },
]

export function serviceTitle(id: string) {
  return SERVICES.find((s) => s.id === id)?.title ?? id
}

export const NURSES: Nurse[] = [
  {
    id: 'n1',
    name: 'أ. منى عبد الرحمن',
    gender: 'female',
    title: 'ممرضة أخصائية عناية مركزة',
    specialties: ['post-op', 'wound-care', 'injections'],
    governorate: 'القاهرة',
    area: 'مدينة نصر',
    coverageGovernorates: ['القاهرة', 'القليوبية'],
    coordinates: { lat: 30.0626, lng: 31.3468 },
    rating: 4.9,
    reviews: 214,
    experienceYears: 11,
    verified: true,
    available: true,
    bio: 'خبرة واسعة في رعاية ما بعد العمليات والعناية بالجروح، حاصلة على بكالوريوس التمريض وعضوة نقابة التمريض.',
    languages: ['العربية', 'الإنجليزية'],
    completedSessionsCount: 3,
    walletBalance: 70, // 100 EGP welcome - 30 EGP (3 sessions)
  },
  {
    id: 'n2',
    name: 'أ. أحمد فتحي',
    gender: 'male',
    title: 'مسعف ومساعد رعاية طوارئ',
    specialties: ['emergency', 'injections', 'elderly'],
    governorate: 'الجيزة',
    area: 'الدقي',
    coverageGovernorates: ['الجيزة', 'القاهرة'],
    coordinates: { lat: 30.0384, lng: 31.2119 },
    rating: 4.7,
    reviews: 138,
    experienceYears: 8,
    verified: true,
    available: true,
    bio: 'مسعف معتمد بخبرة في التعامل مع الحالات الطارئة والإسعافات الأولية ورعاية كبار السن.',
    languages: ['العربية'],
    completedSessionsCount: 5,
    walletBalance: 50,
  },
  {
    id: 'n3',
    name: 'أ. سارة إبراهيم',
    gender: 'female',
    title: 'ممرضة رعاية أمومة وأطفال',
    specialties: ['newborn', 'injections'],
    governorate: 'الإسكندرية',
    area: 'سموحة',
    coverageGovernorates: ['الإسكندرية', 'البحيرة'],
    coordinates: { lat: 31.2156, lng: 29.9553 },
    rating: 5.0,
    reviews: 176,
    experienceYears: 9,
    verified: true,
    available: false,
    bio: 'متخصصة في رعاية حديثي الولادة والأم بعد الولادة، ودعم الرضاعة الطبيعية ومتابعة نمو الطفل.',
    languages: ['العربية', 'الإنجليزية'],
    completedSessionsCount: 2,
    walletBalance: 80,
  },
  {
    id: 'n4',
    name: 'أ. كريم منصور',
    gender: 'male',
    title: 'أخصائي علاج طبيعي',
    specialties: ['physio', 'elderly'],
    governorate: 'القاهرة',
    area: 'المعادي',
    coverageGovernorates: ['القاهرة', 'الجيزة'],
    coordinates: { lat: 29.9602, lng: 31.2569 },
    rating: 4.8,
    reviews: 95,
    experienceYears: 7,
    verified: true,
    available: true,
    bio: 'أخصائي علاج طبيعي متخصص في إعادة التأهيل الحركي بعد الإصابات والعمليات وكبار السن.',
    languages: ['العربية', 'الإنجليزية'],
    completedSessionsCount: 1,
    walletBalance: 90,
  },
  {
    id: 'n5',
    name: 'أ. هبة سمير',
    gender: 'female',
    title: 'ممرضة رعاية منزلية',
    specialties: ['wound-care', 'injections', 'elderly'],
    governorate: 'الجيزة',
    area: '6 أكتوبر',
    coverageGovernorates: ['الجيزة'],
    coordinates: { lat: 29.9723, lng: 30.9575 },
    rating: 4.6,
    reviews: 82,
    experienceYears: 6,
    verified: true,
    available: true,
    bio: 'ممرضة رعاية منزلية بخبرة في غيار الجروح وإعطاء الحقن والعناية اليومية بالمرضى.',
    languages: ['العربية'],
    completedSessionsCount: 0,
    walletBalance: 100, // ممرضة جديدة لديها الرصيد الترحيبي كاملاً
  },
  {
    id: 'n6',
    name: 'أ. محمود شعبان',
    gender: 'male',
    title: 'ممرض عناية ما بعد الجراحة',
    specialties: ['post-op', 'wound-care'],
    governorate: 'الدقهلية',
    area: 'المنصورة',
    coverageGovernorates: ['الدقهلية', 'دمياط', 'الغربية'],
    coordinates: { lat: 31.0409, lng: 31.3785 },
    rating: 4.5,
    reviews: 64,
    experienceYears: 5,
    verified: true,
    available: true,
    bio: 'ممرض متخصص في متابعة المرضى بعد العمليات الجراحية والعناية بالجروح والغيار.',
    languages: ['العربية'],
    completedSessionsCount: 4,
    walletBalance: 60,
  },
  {
    id: 'n7',
    name: 'أ. فاطمة الزهراء علي',
    gender: 'female',
    title: 'ممرضة رعاية مسنين وعناية عامة',
    specialties: ['elderly', 'wound-care', 'injections'],
    governorate: 'أسيوط',
    area: 'حي شرق',
    coverageGovernorates: ['أسيوط', 'المنيا', 'سوهاج'],
    coordinates: { lat: 27.1809, lng: 31.1837 },
    rating: 4.9,
    reviews: 89,
    experienceYears: 8,
    verified: true,
    available: true,
    bio: 'خبرة متميزة في مرافقة كبار السن وإعطاء المحاليل ومتابعة قياسات الضغط والسكر بالصعيد.',
    languages: ['العربية'],
    completedSessionsCount: 0,
    walletBalance: 100,
  },
  {
    id: 'n8',
    name: 'أ. ياسر عبد العظيم',
    gender: 'male',
    title: 'مسعف طوارئ وعناية حادة',
    specialties: ['emergency', 'injections', 'post-op'],
    governorate: 'بورسعيد',
    area: 'حي الشرق',
    coverageGovernorates: ['بورسعيد', 'الإسماعيلية', 'السويس'],
    coordinates: { lat: 31.2653, lng: 32.3019 },
    rating: 4.8,
    reviews: 73,
    experienceYears: 10,
    verified: true,
    available: true,
    bio: 'مسعف طوارئ معتمد في منطقة القناة متخصص في الحالات الإسعافية العاجلة والحقن الوريدي.',
    languages: ['العربية'],
    completedSessionsCount: 2,
    walletBalance: 80,
  },
]

// بيانات الجلسات التجريبية مع آلية التحقق الثنائي (تأكيد الوصول ورمز التحقق OTP) وخصم 10 ج.م عمولة المنصة
export const DEMO_BOOKINGS: SessionBooking[] = [
  {
    id: 's-101',
    patientName: 'محمد عبد الله',
    patientPhone: '01012345678',
    nurseId: 'n1',
    nurseName: 'أ. منى عبد الرحمن',
    service: 'غيار الجروح والتقرحات',
    serviceId: 'wound-care',
    date: '2026-09-24',
    time: '11:00 ص',
    status: 'completed_by_nurse',
    governorate: 'القاهرة',
    area: 'مدينة نصر',
    address: 'شارع عباس العقاد، عمارة 14، الدور الثالث',
    coordinates: { lat: 30.0571, lng: 31.3412 },
    completionCode: '5182',
    verificationCode: '5182',
    arrivalConfirmed: true,
    arrivedAt: '2026-09-24 11:05 ص',
    platformCommission: 10,
    commissionDeducted: false, // تُخصم الـ 10 ج.م فور تأكيد المريض للإتمام
    completedAt: '2026-09-24 11:45 ص',
    nurseNotes: 'تم تعقيم الجرح بالكامل ووضع الغيار المعقم ومتابعة نبض المريض. الجرح في حالة تعافٍ ممتازة.',
    vitalSigns: {
      pulse: '76 نبضة/د',
      bloodPressure: '120/80',
      temperature: '37.1 °م',
    },
  },
  {
    id: 's-102',
    patientName: 'سعاد إبراهيم',
    patientPhone: '01123456789',
    nurseId: 'n1',
    nurseName: 'أ. منى عبد الرحمن',
    service: 'رعاية ما بعد العمليات',
    serviceId: 'post-op',
    date: '2026-09-23',
    time: '04:00 م',
    status: 'confirmed_completed',
    governorate: 'القاهرة',
    area: 'مصر الجديدة',
    address: 'ميدان روكسي، شارع الأهرام',
    coordinates: { lat: 30.0924, lng: 31.3211 },
    completionCode: '8391',
    verificationCode: '8391',
    arrivalConfirmed: true,
    arrivedAt: '2026-09-23 04:08 م',
    platformCommission: 10,
    commissionDeducted: true, // تم خصم الـ 10 ج.م من رصيد الممرض تلقائياً
    completedAt: '2026-09-23 04:50 م',
    confirmedAt: '2026-09-23 05:02 م',
    nurseNotes: 'تمت إزالة الغرز الجراحية بأمان واختبار الحركة والتنفس.',
    vitalSigns: {
      pulse: '72 نبضة/د',
      bloodPressure: '125/82',
      temperature: '36.8 °م',
    },
  },
  {
    id: 's-103',
    patientName: 'طارق حسام',
    patientPhone: '01234567890',
    nurseId: 'n2',
    nurseName: 'أ. أحمد فتحي',
    service: 'إعطاء الحقن والمحاليل',
    serviceId: 'injections',
    date: '2026-09-24',
    time: '02:30 م',
    status: 'in_progress',
    governorate: 'الجيزة',
    area: 'الدقي',
    address: 'شارع مصدق، عمارة 8',
    coordinates: { lat: 30.0411, lng: 31.2052 },
    completionCode: '7419',
    verificationCode: '7419',
    arrivalConfirmed: true,
    arrivedAt: '2026-09-24 02:35 م',
    platformCommission: 10,
    commissionDeducted: false,
    nurseNotes: 'الممرض في الموقع حالياً — تم فحص الروشتة وجارٍ تركيب المحلول.',
  },
  {
    id: 's-104',
    patientName: 'أشرف محمود',
    patientPhone: '01512345678',
    nurseId: 'n4',
    nurseName: 'أ. كريم منصور',
    service: 'جلسات العلاج الطبيعي',
    serviceId: 'physio',
    date: '2026-09-24',
    time: '06:00 م',
    status: 'nurse_en_route',
    governorate: 'القاهرة',
    area: 'المعادي',
    address: 'شارع 9، المعادي',
    coordinates: { lat: 29.9592, lng: 31.2612 },
    completionCode: '9034',
    verificationCode: '9034',
    arrivalConfirmed: false,
    platformCommission: 10,
    commissionDeducted: false,
    nurseNotes: 'الممرض في الطريق إلى المريض، الوصول المقدر خلال 15 دقيقة.',
  },
]

export const DEMO_RECORDS: MedicalRecord[] = [
  { id: 'r1', title: 'تقرير جلسة غيار الجرح ومؤشرات التعافي', type: 'تقرير', date: '2026-09-24', encrypted: true },
  { id: 'r2', title: 'تحليل سكر تراكمي HbA1c', type: 'تحليل', date: '2026-09-10', encrypted: true },
  { id: 'r3', title: 'أشعة رنين مغناطيسي على الفقرات', type: 'أشعة', date: '2026-08-28', encrypted: true },
  { id: 'r4', title: 'روشتة ومواعيد جرعات المضاد الحيوي', type: 'روشتة', date: '2026-09-18', encrypted: true },
]

// محفظة أرباح تجريبية للممرض مبنية على رصيد ترحيبي 100 جنيه وخصم 10 جنيه لكل جلسة مؤكدة
export const DEMO_NURSE_WALLET: NurseWallet = {
  nurseId: 'n1',
  nurseName: 'أ. منى عبد الرحمن',
  initialWelcomeCredit: 100, // 100 جنيه هدية ترحيبية تكفي لـ 10 جلسات مجانية
  currentBalance: 70, // الرصيد المتبقي = 70 جنيه مصري
  completedSessionsCount: 3, // أتمت 3 جلسات مؤكدة
  totalCommissionDeducted: 30, // خصم 30 ج.م (3 * 10 ج.م)
  remainingSessionsQuota: 7, // يتبقى لها 7 جلسات قبل الحاجة لإعادة الشحن
  needsRecharge: false,
  transactions: [
    {
      id: 'tx-1',
      date: '2026-09-20',
      type: 'welcome_credit',
      amount: 100,
      description: 'هدية ترحيبية: رصيد مبدئي 100 جنيه (يكفي لتنفيذ أول 10 جلسات)',
      balanceAfter: 100,
    },
    {
      id: 'tx-2',
      date: '2026-09-22',
      type: 'session_commission_deduction',
      amount: -10,
      description: 'خصم عمولة تطبيق رحمة عن الجلسة المكتملة والمؤكدة #s-100',
      sessionId: 's-100',
      balanceAfter: 90,
    },
    {
      id: 'tx-3',
      date: '2026-09-23',
      type: 'session_commission_deduction',
      amount: -10,
      description: 'خصم عمولة تطبيق رحمة عن الجلسة المكتملة والمؤكدة #s-102',
      sessionId: 's-102',
      balanceAfter: 80,
    },
    {
      id: 'tx-4',
      date: '2026-09-24',
      type: 'session_commission_deduction',
      amount: -10,
      description: 'خصم عمولة تطبيق رحمة عن الجلسة المكتملة والمؤكدة #s-099',
      sessionId: 's-099',
      balanceAfter: 70,
    },
  ],
}

export const SESSION_STATUS_MAP: Record<
  string,
  { label: string; color: string; step: number; description: string }
> = {
  pending: {
    label: 'طلب جديد',
    color: 'bg-muted text-muted-foreground border-border',
    step: 1,
    description: 'تم إرسال طلب الحجز وفي انتظار تأكيد الممرض.',
  },
  confirmed: {
    label: 'تم تأكيد الموعد',
    color: 'bg-blue-500/10 text-blue-700 border-blue-500/30',
    step: 2,
    description: 'وافق الممرض على الجلسة ومستعد للموعد المحدد.',
  },
  nurse_en_route: {
    label: 'الممرض في الطريق',
    color: 'bg-amber-500/10 text-amber-700 border-amber-500/30',
    step: 3,
    description: 'الممرض تحرك نحو موقعك الجغرافي المسجل عبر GPS.',
  },
  nurse_arrived: {
    label: 'وصل الممرض إلى الموقع',
    color: 'bg-indigo-500/10 text-indigo-700 border-indigo-500/30',
    step: 4,
    description: 'تم تأكيد وصول الممرض إلى الموقع، وجارٍ بدء تقديم الرعاية.',
  },
  in_progress: {
    label: 'الجلسة جارية الآن',
    color: 'bg-purple-500/10 text-purple-700 border-purple-500/30',
    step: 5,
    description: 'الممرض متواجد في المنزل ويقدم الخدمة التمريضية.',
  },
  completed_by_nurse: {
    label: 'أنهى الممرض الجلسة — بانتظار التأكيد',
    color: 'bg-emerald-500/10 text-emerald-700 border-emerald-500/30',
    step: 6,
    description: 'سجّل الممرض انتهاء الجلسة، في انتظار إدخال رمز التحقق لتأكيد الجلسة رسمياً وخصم 10 ج.م عمولة التطبيق.',
  },
  confirmed_completed: {
    label: 'تمت الجلسة وتأكيدها بنجاح',
    color: 'bg-primary/10 text-primary border-primary/30',
    step: 7,
    description: 'تم تأكيد إتمام الجلسة رسمياً برمز التحقق وخصم 10 جنيه عمولة التطبيق من رصيد الممرض.',
  },
  cancelled: {
    label: 'ملغاة',
    color: 'bg-destructive/10 text-destructive border-destructive/30',
    step: 0,
    description: 'تم إلغاء هذه الجلسة.',
  },
}
